-- Seed EXERCISES table
INSERT INTO exercises (id, name, muscle_group, difficulty, image_url, instructions, common_mistakes) VALUES
(1, 'Push-Ups', 'chest', 'beginner', '/images/MONDAY/pushup.png', '', ''),
(2, 'Brick Chest Press', 'chest', 'beginner', '/images/MONDAY/Brick Chest Press.png', '', ''),
(3, 'Brick Chest Fly', 'chest', 'beginner', '/images/MONDAY/Brick Chest Fly.png', '', ''),
(4, 'Alternating Bicep Curl', 'arms', 'beginner', '/images/MONDAY/Alternating Bicep Curl.png', '', ''),
(5, 'Tricep Extension', 'arms', 'beginner', '/images/MONDAY/Tricep Extension.png', '', ''),
(6, 'Hammer Curl', 'arms', 'beginner', '/images/MONDAY/Hammer Curl.png', '', ''),
(7, 'Wrist Curl', 'forearms', 'beginner', '/images/MONDAY/Wrist Curl.png', '', ''),
(8, 'Farmer Hold', 'forearms', 'beginner', '/images/MONDAY/Farmer Hold.png', '', ''),
(9, 'Bent Over Rows', 'back', 'beginner', '/images/TUESDAY/Bent Over Row.png', '', ''),
(10, 'Decline Brick Press', 'back', 'beginner', '/images/TUESDAY/Decline Brick Press.png', '', ''),
(11, 'Shoulder Press', 'shoulders', 'beginner', '/images/TUESDAY/Shoulder Press.png', '', ''),
(12, 'Lateral Raises', 'shoulders', 'beginner', '/images/TUESDAY/Lateral Raise.png', '', ''),
(13, 'Pike Push-Ups', 'shoulders', 'beginner', '/images/TUESDAY/Pike Push-Up.png', '', ''),
(14, 'Rear Delt Fly', 'shoulders', 'beginner', '/images/TUESDAY/Rear Delt Fly.png', '', ''),
(15, 'Brick Squeeze Press', 'shoulders', 'beginner', '/images/TUESDAY/Brick Squeeze Press.png', '', ''),
(16, 'Long Arm Crunches', 'abs', 'beginner', '/images/WEDNESDAY/Long Arm Crunch.png', '', ''),
(17, 'Heel Taps', 'abs', 'beginner', '/images/WEDNESDAY/Heel Taps.png', '', ''),
(18, 'Mountain Climbers', 'abs', 'beginner', '/images/WEDNESDAY/Mountain Climber.png', '', ''),
(19, 'Reverse Crunch', 'abs', 'beginner', '/images/WEDNESDAY/Reverse Crunch.png', '', ''),
(20, 'Plank', 'abs', 'beginner', '/images/WEDNESDAY/Plank.png', '', ''),
(21, 'Squats', 'legs', 'beginner', '/images/FRIDAY/Squat.png', '', ''),
(22, 'Backward Lunges', 'legs', 'beginner', '/images/FRIDAY/Backward Lunge.png', '', ''),
(23, 'Glute Bridge', 'legs', 'beginner', '/images/FRIDAY/Glute Bridge.png', '', ''),
(24, 'Side Lunges', 'legs', 'beginner', '/images/FRIDAY/Side Lunge.png', '', ''),
(25, 'Calf Raises', 'legs', 'beginner', '/images/FRIDAY/Calf Raise.png', '', ''),
(26, 'Wall Sit', 'legs', 'beginner', '/images/FRIDAY/Wall Sit.png', '', ''),
(27, 'Decline Push-Ups', 'chest', 'beginner', '/images/SATURDAY/Decline Push Up.png', '', ''),
(28, 'Hindu Push-Ups', 'chest', 'beginner', '/images/SATURDAY/Hindu Push-Up.png', '', ''),
(29, 'Brick Squeeze Press', 'chest', 'beginner', '/images/SATURDAY/Brick Squeeze Press.png', '', ''),
(30, 'Arnold Press', 'shoulders', 'beginner', '/images/SATURDAY/Arnold Press.png', '', ''),
(31, 'Tricep Dips', 'arms', 'beginner', '/images/SATURDAY/Tricep Dip.png', '', ''),
(32, 'Dumbbell Kickbacks', 'arms', 'beginner', '/images/SATURDAY/Dumbbell Kickbacks.png', '', ''),
(33, 'Hammer Curl', 'arms', 'beginner', '/images/SATURDAY/Hammer Curl.png', '', ''),
(34, 'Reverse Wrist Curl', 'forearms', 'beginner', '/images/SATURDAY/Reverse Wrist Curl.png', '', ''),
(35, 'Farmer Hold', 'forearms', 'beginner', '/images/SATURDAY/Farmer Hold.png', '', ''),
(36, 'Floor Press', 'chest', 'beginner', '/images/SUNDAY/Floor Press.png', '', ''),
(37, 'Bent Over Rows', 'back', 'beginner', '/images/SUNDAY/Bent Over Row.png', '', ''),
(38, 'Step-Ups', 'legs', 'beginner', '/images/SUNDAY/Step-Up.png', '', ''),
(39, 'Backward Lunges', 'legs', 'beginner', '/images/SUNDAY/Backward Lunge.png', '', ''),
(40, 'Push-Ups', 'chest', 'beginner', '/images/SUNDAY/Push-Up.png', '', ''),
(41, 'Hammer Curl', 'arms', 'beginner', '/images/SUNDAY/Hammer Curl.png', '', ''),
(42, 'Plank', 'abs', 'beginner', '/images/SUNDAY/Plank.png', '', ''),
(43, 'Burpees', 'fullbody', 'beginner', '/images/SUNDAY/Burpee.png', '', ''),
(44, 'Farmer Hold', 'forearms', 'beginner', '/images/SUNDAY/Farmer Hold.png', '', '')
ON CONFLICT (id) DO UPDATE SET 
  name = EXCLUDED.name,
  muscle_group = EXCLUDED.muscle_group,
  image_url = EXCLUDED.image_url;